# Generated by Django 4.2.11 on 2024-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo_url',
            field=models.CharField(verbose_name='Photo'),
        ),
    ]
